"""Offline tests for the release-specific ChatGPT install adaptation."""
import hashlib
import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

ADAPTER_PATH = Path(__file__).resolve().parents[1] / 'scripts/adapt-chatgpt-install.py'
spec = importlib.util.spec_from_file_location('chatgpt_adapter', ADAPTER_PATH)
adapter = importlib.util.module_from_spec(spec)
spec.loader.exec_module(adapter)


class ChatGPTRecoveryTests(unittest.TestCase):
    def fixture(self):
        sources = {
            'postinst': b'#!/bin/sh\nset -e\nDEFAULTS_FILE=/etc/default/chatgpt\n'
                        b'install_key() { echo apt; }\ninstall_key\n'
                        b'update-desktop-database >/dev/null 2>&1 || true\n'
                        b'if test -f /etc/apparmor.d/abi/4.0; then\n'
                        b'  echo apparmor-preserved\nfi\n',
            'prerm': b'#!/bin/sh\nif [ "$1" = remove ]; then echo removal; fi\n',
            'postrm': b'#!/bin/sh\nset -e\nSOURCES_FILE=/etc/apt/example\n'
                       b'if [ "$1" = purge ]; then rm -f "$SOURCES_FILE"; fi\n'
                       b'update-desktop-database >/dev/null 2>&1 || true\n',
        }
        content = b'# Generated by debtap\n'
        for name, source in sources.items():
            content += b'\n_debtap_' + name.encode() + b'() (\n: \n' + source
            content += b'\n)\n' + adapter.HOOKS[name].encode() + b'() { :; }\n'
        hashes = {name: hashlib.sha256(source).hexdigest() for name, source in sources.items()}
        return content, hashes

    def test_removes_apt_as_complete_block_and_preserves_apparmor(self):
        content, hashes = self.fixture()
        with patch.object(adapter, 'HASHES', hashes):
            cleaned = adapter.adapt(content)
        adapter.check(cleaned)
        self.assertIn(b'if test -f /etc/apparmor.d/abi/4.0; then', cleaned)
        self.assertIn(b'echo removal', cleaned)
        self.assertNotIn(b'install_key', cleaned)
        self.assertNotIn(b'/etc/apt', cleaned)

    def test_changed_maintainer_script_is_rejected(self):
        content, hashes = self.fixture()
        with patch.object(adapter, 'HASHES', hashes):
            with self.assertRaisesRegex(ValueError, 'differs from the reviewed'):
                adapter.adapt(content.replace(b'echo removal', b'echo changed'))

    def test_additional_maintainer_script_is_rejected(self):
        content, hashes = self.fixture()
        with patch.object(adapter, 'HASHES', hashes):
            with self.assertRaisesRegex(ValueError, 'Unexpected maintainer'):
                adapter.adapt(content + b'\n_debtap_preinst() ( : )\n')

    def test_failed_editor_leaves_original_untouched(self):
        with tempfile.TemporaryDirectory() as directory:
            install = Path(directory, '.INSTALL')
            original = self.fixture()[0]
            install.write_bytes(original)
            result = subprocess.run(['python3', str(ADAPTER_PATH), str(install)],
                                    capture_output=True)
            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(install.read_bytes(), original)

    def test_check_refuses_unclean_or_invalid_install_script(self):
        for content in (b'post_install() { :; }\n',
                        adapter.CLEAN_HEADER + b'# /etc/apt\n',
                        adapter.CLEAN_HEADER + b'else\n'):
            with self.subTest(content=content):
                with self.assertRaises((ValueError, subprocess.CalledProcessError)):
                    adapter.check(content)
